### PR TITLE
Bulk stream deployment: fix platform field

### LINKED ISSUE #1277: Bulk stream deployment: select a platform is not working
As a user, when I attempt to deploy streams in bulk with >1 platforms, click on edit deployment properties and select a platform is broken.

### PR DESCRIPTION
**Pull request by oodamien**
Resolves #1277

### CODE REVIEW

File: ui/src/app/streams/streams/deployment-properties/deployment-properties.component.ts [hunk 1]
```diff
@@ -76,8 +77,11 @@ export class DeploymentPropertiesComponent implements OnInit, OnDestroy {
       if (this.stream.deploymentProperties.platformName) {
         this.deploymentPlatform.setValue(this.stream.deploymentProperties.platformName);
       }
+      if (this.stream.deploymentProperties[keyPlatform]) {
+        this.deploymentPlatform.setValue(this.stream.deploymentProperties[keyPlatform])
```
Comment (jvalkeal) [inline ui/src/app/streams/streams/deployment-properties/deployment-properties.component.ts]: with this addition, what exactly is above `this.deploymentPlatform.setValue(this.stream.deploymentProperties.platformName)` supposed to do?

Comment (oodamien) [reply ui/src/app/streams/streams/deployment-properties/deployment-properties.component.ts]: I didn't want to remove this line but I think it's dead code...

**Comment by jvalkeal** [comment]
ok, merging...
